"use client";
import "./login.scss";
import { useRouter } from "next/navigation";

// export const metadata = {
//   title: 'Login | TasksFor',
//   description: 'Generated by create next app',
// }

export default function LoginPage() {
  const router = useRouter();

  return (
    <>
      <section>
        <form onSubmit={(e) => {router.push('/'); e.preventDefault();}}>
          <div className="form-container">
            <h1>LOGIN</h1>
            <div className="form-login">

              <div className="group-input">
                <label>Email:</label>
                <input type="text" />
              </div>
              <div className="group-input">
                <label>Senha:</label>
                <input type="text" />
              </div>
              
            </div>
          </div>

          <button type="submit">Logar</button>
        </form>
      </section>
    </>
  )
}