"use client";

import "../login-register.scss";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { useSignInWithEmailAndPassword } from 'react-firebase-hooks/auth';
import { auth } from "../../../../services/firebase";

// export const metadata = {
//   title: 'Login | TasksFor',
//   description: 'Generated by create next app',
// }

export default function LoginPage() {
  const router = useRouter();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [signInWithEmailAndPassword, user, loading, error] = useSignInWithEmailAndPassword(auth);

  async function logar() {
    try {
      await signInWithEmailAndPassword(email, password);
      console.log('user >> ', user);
      console.log('error >> ', error);
    } catch(err) {
      console.log('err >> ', err);
    }
    router.push('/');
  }

  // if (user)
  //   console.log(user)
  
  // if (loading) 
  //   return <p>C A R R E G A N D O . . .</p>

  return (
    <>
      <section>
        <form onSubmit={(e) => { logar(), e.preventDefault() }}>
          <div className="form-container">
            <h1>LOGIN</h1>
            <div className="form-login">

              <div className="group-input">
                <label>Email:</label>
                <input type="text" onChange={(email) => setEmail(email.target.value)}/>
              </div>
              <div className="group-input">
                <label>Senha:</label>
                <input type="password" onChange={(password) => setPassword(password.target.value)}/>
              </div>
              
            </div>
            <p onClick={(e)=> {router.push('/register'), e.preventDefault()}}>Cadastrar uma nova conta</p>
          </div>

          <button type="submit">Logar</button>
        </form>
      </section>
    </>
  )
}