"use client";

import { useRouter } from "next/navigation"

export const metadata = {
  title: 'Login | TasksFor',
  description: 'Generated by create next app',
}

export default function LoginPage() {
  const router = useRouter();

  return (
    <>
      <form onSubmit={(e) => {router.push('/'); e.preventDefault();}}>
        <div>
          <label>Email:</label>
          <input type="text" />
            <br />
          <label>Senha:</label>
          <input type="text" />
            <br />
          <button type="submit">Logar</button>
        </div>
      </form>
    </>
  )
}