"use client";
import Link from "next/link";
import { getUsers } from "../services/users-service"

export const metadata = {
  title: 'Equipe | TasksFor',
  description: 'Generated by create next app',
}

export default async function UsersPage() {
  const users = await getUsers();

  return (
    <>
      <p>Pagina de lista de Users</p>
      <h1>Sua Equipe:</h1>
      <ul>
        {users.map((user: any) => <li key={user.id}>
          <Link href={`/users/${user.id}`}> {user.first_name} {user.last_name} </Link>
        </li>)}
      </ul>
    </>
  )
}