"use client";

import './user.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSquare, faCheckSquare } from '@fortawesome/free-regular-svg-icons';

import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);

import { useEffect, useState } from 'react';
import { IUser } from '@/app/interfaces/user.interface';

// export const metadata = {
//   title: 'Equipe | TasksFor',
//   description: 'Generated by create next app',
// }

export default function UsersPage() {

  const [lstUser, setLstUser] = useState<IUser[]>([]);

  useEffect(() => {
    getAllUsers();
  }, []);

  function getAllUsers() {
    fetch(`api/user_api`)
      .then((res) => res.json())
      .then((data) => {
        setLstUser(data);
      })
  }
  
  return (
    <>
      <section className="container-title">
        <h2>Sua Equipe</h2>
        <button>
          <FontAwesomeIcon icon="plus"/>
        </button>
      </section>

      <section className="container-list-user">
        {lstUser?.length > 0 ? (
            lstUser.map((user: IUser) => (
              <div key={user.id} className="box-card">
                <div className="card-info">
                  <p>{user.name}</p>
                  <p><strong>• Email:</strong>{user.email}</p>
                  <p><strong>• Setor:</strong> Desenvolvimento</p>
                  <p><strong>• Permissão:</strong>{user.role}</p>
                  <p>
                    <strong>• Tarefas:</strong> 
                    <span>
                      <FontAwesomeIcon icon={faSquare}/>
                      <span>10</span>
                    </span>
                    <span>
                      <FontAwesomeIcon icon={faCheckSquare}/>
                      <span>10</span>
                    </span>
                  </p>
                </div>
                <div className="card-actions">
                  <button>Excluir Usuário</button>
                  <button>Editar Usuário</button>
                </div>
              </div>
            ))
          ) : (
            <p>Nenhum usuário encontrado.</p>
          )}
      </section>
    </>
  )
}